export const metadata = {
  title: "About us | Next Movies",
  description: "Generated by Next.js",
};

export default function aboutUs() {
  console.log("hello wolrd");
  return (
    <div>
      <h1>About us!</h1>
    </div>
  );
}
